[package]
name = "unbox"
version = "0.1.0"
authors = ["Leo Zhang <leo@leozhang.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyset = "0.4.4"
